In [5]:
import numpy

First import numpy

In [6]:
Myarray = numpy.array([[5,8,3,7]])
twodarray = numpy.array ([[5,8,3,7],[1,2,3,4],[9,8,7,6]])
print(Myarray)
print(twodarray)

[[5 8 3 7]]
[[5 8 3 7]
 [1 2 3 4]
 [9 8 7 6]]


import numpy as np


In [7]:
import numpy as np

In [9]:
np.__version__

'2.5.3'

In [ ]:
#Convert list to array
arr.

0- Dimension array.............. ndim is attributes of array - features of that array 

In [ ]:
arr = np.array(100)


1- Dimension array

In [ ]:
oneD = np.array([1,2,3,4,5])
oneD = np.array(range(1,6))
print(oneD)


#Attributes of array
print(oneD.ndim) #Dimensio of the arrray
print(oneD.shape) #shape of the array in roew or column 
print(oneD.size) # number of elements in the numpy array
print(oneD.itemsize) #size in bytes in the numpy array
print(oneD.dtype) #data type of the elements in numpty array

[1 2 3 4 5]
1
(5,)
5
8
int64


In [16]:
twoD = np.array([[1,2,3,4,5],[5,8,9,7,6]])
print(twoD)


#Attributes of array
print(twoD.ndim) #Dimensio of the arrray
print(twoD.shape) #shape of the array in roew or column 
print(twoD.size) # number of elements in the numpy array
print(twoD.itemsize) #size in bytes in the numpy array
print(twoD.dtype) #data type of the elements in numpty array

[[1 2 3 4 5]
 [5 8 9 7 6]]
2
(2, 5)
10
8
int64


3-Dimensional Array

In [ ]:
threeD =np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(threeD)

#Attributes of array
print(threeD.ndim) #Dimensio of the arrray
print(threeD.shape) #shape of the array in roew or column ....1st- No. of stack , 2nd -no. of rows , 3rd - no. of column
print(threeD.size) # number of elements in the numpy array
print(threeD.itemsize) #size in bytes in the numpy array
print(threeD.dtype) #data type of the elements in numpty array
#No. of stack , no. of rows 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
9
8
int64


Creating Ndarrray with function

In [18]:
#Creating Array with all elements zero
x=np.zeros(5,dtype=float)
x

array([0., 0., 0., 0., 0.])

In [ ]:
#Two dimensional array
x=np.zeros((5,4),dtype=float) #1st attributes is shape of the array ....2nd is type of the array
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#Creating array with all elements ones
x=np.ones(5, dtype =int)
x

array([1, 1, 1, 1, 1])

In [21]:
#Two dimensional array
x=np.ones((5,4),dtype=float) #1st attributes is shape of the array ....2nd is type of the array
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Create 1D array wit evenly spaced numbers between ones 
arr = np.arange(0, 10,2)  #start , stop, step
print (arr)
print(type(arr))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [24]:
arr =np.linspace(0,10,6) #start, stop,num
print(arr)

[ 0.  2.  4.  6.  8. 10.]


In [25]:
#Efficient storage and computation
import numpy as np
import sys 

Lists1 = [1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(List1))
arr = np.array(List1)
print(arr.size*arr.itemsize)
print(arr.nbytes)

NameError: name 'List1' is not defined