In [5]:
#Faster than list
import numpy as np
import time

L1= range(1,100000)
L2= range(1,100000)
A1=np.array(11)
A2=np.array(12)

#operation to be performed on the list
start=time.time()
z=zip(L1,L2)
result1=[x+y for x,y in z]
end = time.time()
print((end - start)*1000)

#operation to be performed on numpy array 
start1 =time.time()
result2=A1+A2
print((time.time()-start)*1000)

9.969472885131836
12.05301284790039


How to use numpy to generate random numbers?

In [ ]:
#Generate 10 random float
import numpy as np
x=np.random.rand(10) #Old API
print(x)

[0.93540958 0.01716356 0.42870131 0.46120625 0.27093099 0.29272714
 0.12790352 0.553075   0.11706291 0.27230434]


In [2]:
#Generate (3x4) vector of random float 
x=np.random.rand(3,4)
print(x)

[[0.21576627 0.46052828 0.32003321 0.57367194]
 [0.12522826 0.12133703 0.98645033 0.62193107]
 [0.43200853 0.5650839  0.94586757 0.55974299]]


In [3]:
#Generate 10 random integer in between 5 to 10
x=np.random.randint(5,10,size=10)
print(x)

[9 8 8 5 7 9 5 8 7 9]


In [8]:
#Generate (3x2) vector to random integer in between 5 to 10
x=np.random.randint(5,11,size=(3,2))
print(x)

[[ 5 10]
 [ 5 10]
 [ 7  5]]


Create a matrix of 3x4 of random number and find its maximum and minimum

In [12]:
np.random.seed(12)
np.random.randint(0,100,size=(3,4))
print(x)
print(x.max())
print(x.min())
print(x.sum())
print(x.mean())


[[0.99391697 0.05421191 0.75664278 0.33357432]
 [0.10862846 0.68772266 0.12707811 0.12933334]
 [0.40794633 0.52773302 0.10551422 0.57536345]]
0.993916968187002
0.054211909072393594
4.807665581343149
0.4006387984452624
