In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,6])
a=x.view()
b=x.copy()
x[0]=42
print(x)
print(x.base)
print(a.base)
print(b.base)
print("if")
print(id(x))
print(id(y))

[42  2  3  4  5  6]
None
[42  2  3  4  5  6]
None


In [7]:
#Reshape the numbers 1 through 9 in a 3*3 grid
#eg. for 9 elements dimension should be 3*3 or 1*9 or 9*1
n = np.arange(1,13)
print(n)
x=n.reshape((3,4))
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
#Rotation of the array
x=np.arange(1,10).reshape(3,3)
x=x.T
print(x)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
#Rotation of the array
np.rot90(m,1)

NameError: name 'm' is not defined

Joining of the two array

In [ ]:
np.concatenate
x=np.array([])