In [ ]:
#np.cancatinate function

In [1]:
import numpy as np
x =np.array([[1,1,1],[2,2,2],[3,3,3]])
y=np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
import numpy as np
x =np.array([[1,1,1],[2,2,2],[3,3,3]])
y=np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=0)

In [ ]:
import numpy as np
x =np.array([[1,1,1],[2,2,2],[3,3,3]])
y=np.array([[4,4,4],[5,5,5]])
np.vstack([x,y],axis=1) #vstack for verticaly

TypeError: vstack() got an unexpected keyword argument 'axis'

In [ ]:
import numpy as np
x =np.array([[1,1,1],[2,2,2],[3,3,3]])
y=np.array([[4,4,4],[5,5,5]])
np.hstack([x,y],axis=1) #hstack for horizontal

In [ ]:
#Spliting the array
x=np.arange(1,13)
np.split(x,4) #4 means equal split in 4 parts 
np.split(x,6) #6 means...................

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [ ]:
x=np.arange(1,10)
np.split(x,[3,5,6])#  #start spliting from 3rd then from 5th then from 6th

[array([1, 2]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([3, 4, 5, 6, 7, 8, 9])]

In [8]:
x=np.arange (1,10).reshape([3,3])
print(x)
np.hsplit(x,3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [9]:
x=np.arange (1,11).reshape([2,5])
print(x)
np.hsplit(x,[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[ 3,  4,  5],
        [ 8,  9, 10]])]

In [12]:
#vsplit
x=np.arange (1,11).reshape([5,2])
print(x)
np.vsplit(x,[1,3])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[array([[1, 2]]),
 array([[3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10]])]

Data types for ndarrays
bool_
int_   Default integer type
intc  identical to C intn
intp
int8 byte(-128 to 127)
int16
int32
int64
uint8 Unsigned(0to255)
uint16
unit32
unit64
float_
float16
float32 


Casting 

In [13]:
x=np.array(['1.2','23.3','4.5'],dtype=np.string_)
y=x.astype(np.float64)

AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.

Arithmetic with numpy arrays

In [ ]:
#Multiplication
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[2,2,2],[3,3,3]])
x*y

array([[ 2,  4,  6],
       [12, 15, 18]])

In [16]:
x-y

array([[-1,  0,  1],
       [ 1,  2,  3]])

In [21]:
1/x

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [22]:
x*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36]])